services:
  db:
    image: postgres:alpine
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=app
    volumes:
      - ./app/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
  app:
    image: app
    build: .
    ports:
      - '9001:9001'
    environment:
      - APP_PORT=9001
      - APP_HOST=0.0.0.0
      - DB_URL=postgres://user:pass@db:5432/app
    depends_on:
      - db
    restart: unless-stopped
 
 
